// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TagsController from "./tags_controller"
application.register("tags", TagsController)

import VacancyController from "./vacancy_controller"
application.register("vacancies", VacancyController)

import GradeController from "./grade_controller"
application.register("grades", GradeController)
