default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development_database
  username: ivansizyh
  password: 123456
  host: localhost

test:
  <<: *default
  adapter: postgresql
  database: test_database
  username: ivansizyh
  password: 123456
  host: localhost

production:
  <<: *default
  database: production_database
  username: ivansizyh
  password: 123456
  host: localhost