default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teachinterrogate_dev
  username: ivansizyh
  password: 123456
  host: localhost
  template: template0

test:
  <<: *default
  adapter: postgresql
  database: teachinterrogate_test
  username: ivansizyh
  password: 123456
  host: localhost
  